In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Functions
### Function definitions

In [4]:
def student_info(name, age = 18):
    print(name, age)





### Function calling

In [5]:
student_info("John")
student_info("Alice",22)

John 18
Alice 22


### Math module

In [6]:
import math

a = math.sqrt(45)
print(a)

6.708203932499369


## Numpy

In [7]:
!pip install numpy


In [8]:
x = np.array([1,4,3])

y = np.array([[3,5,2], [2,6,3]])

z = np.array([[[2,8,4],[3,6,2],[4,1,2]]])

print(z)

[[[2 8 4]
  [3 6 2]
  [4 1 2]]]


## Pandas

In [9]:
import pandas as pd #importing pandas library



In [10]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age" : [23,25,21],
    "Salary" : [45642,73453,64353]
}

print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [23, 25, 21], 'Salary': [45642, 73453, 64353]}


In [11]:
print(pd.DataFrame(data))

      Name  Age  Salary
0    Alice   23   45642
1      Bob   25   73453
2  Charlie   21   64353


In [12]:
df = pd.read_csv("D:/Basicsd/Basics of Python/Day-3/uber_ncr_ride_bookings.csv")

print(df)

              Date      Time    Booking ID   Booking Status   Customer ID  \
0       2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"   
1       2024-11-29  18:01:39  "CNR1326809"       Incomplete  "CID4604802"   
2       2024-08-23  08:56:10  "CNR8494506"        Completed  "CID9202816"   
3       2024-10-21  17:17:25  "CNR8906825"        Completed  "CID2610914"   
4       2024-09-16  22:08:00  "CNR1950162"        Completed  "CID9933542"   
...            ...       ...           ...              ...           ...   
149995  2024-11-11  19:34:01  "CNR6500631"        Completed  "CID4337371"   
149996  2024-11-24  15:55:09  "CNR2468611"        Completed  "CID2325623"   
149997  2024-09-18  10:55:15  "CNR6358306"        Completed  "CID9925486"   
149998  2024-10-05  07:53:34  "CNR3030099"        Completed  "CID9415487"   
149999  2024-03-10  15:38:03  "CNR3447390"        Completed  "CID4108667"   

         Vehicle Type         Pickup Location      Drop Location  Avg VTAT 

In [13]:
df.head()

Date      Time    Booking ID   Booking Status   Customer ID  \
0  2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"   
1  2024-11-29  18:01:39  "CNR1326809"       Incomplete  "CID4604802"   
2  2024-08-23  08:56:10  "CNR8494506"        Completed  "CID9202816"   
3  2024-10-21  17:17:25  "CNR8906825"        Completed  "CID2610914"   
4  2024-09-16  22:08:00  "CNR1950162"        Completed  "CID9933542"   

    Vehicle Type      Pickup Location      Drop Location  Avg VTAT  Avg CTAT  \
0          eBike          Palam Vihar            Jhilmil       NaN       NaN   
1       Go Sedan        Shastri Nagar  Gurgaon Sector 56       4.9      14.0   
2           Auto              Khandsa      Malviya Nagar      13.4      25.8   
3  Premier Sedan  Central Secretariat           Inderlok      13.1      28.5   
4           Bike     Ghitorni Village        Khan Market       5.3      19.6   

   ...  Reason for cancelling by Customer Cancelled Rides by Driver  \
0  ...                                NaN                       NaN   
1  ...                                NaN                       NaN   
2  ...                                NaN                       NaN   
3  ...                                NaN                       NaN   
4  ...                                NaN                       NaN   

   Driver Cancellation Reason Incomplete Rides  Incomplete Rides Reason  \
0                         NaN              NaN                      NaN   
1                         NaN              1.0        Vehicle Breakdown   
2                         NaN              NaN                      NaN   
3                         NaN              NaN                      NaN   
4                         NaN              NaN                      NaN   

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN   
1         237.0           5.73             NaN              NaN   
2         627.0          13.58             4.9              4.9   
3         416.0          34.02             4.6              5.0   
4         737.0          48.21             4.1              4.3   

   Payment Method  
0             NaN  
1             UPI  
2      Debit Card  
3             UPI  
4             UPI  

[5 rows x 21 columns]