## Assignment - Day -3

In [8]:
import numpy as np
import pandas as pd

In [9]:

matrix = np.array([[1,3,5],
             [4,6,2],
             [4,2,1]])

matrix_double = matrix * 2

print(f"2D Matrix :\n {matrix}")
print(f"2D Matrix * 2 : \n{matrix_double}")

2D Matrix :
 [[1 3 5]
 [4 6 2]
 [4 2 1]]
2D Matrix * 2 : 
[[ 2  6 10]
 [ 8 12  4]
 [ 8  4  2]]


In [10]:
#2

dictionary = {"product_name":["Basket", "Bag", "Trolley"], "price":[200, 500, 2000], "stock_quantity":[56, 35, 454]}

df = pd.DataFrame(dictionary)

print(df)

  product_name  price  stock_quantity
0       Basket    200              56
1          Bag    500              35
2      Trolley   2000             454


In [11]:
#3
df2 = df[df["stock_quantity"]> 50]
print(df2)

  product_name  price  stock_quantity
0       Basket    200              56
2      Trolley   2000             454
